//// Renders a declaration as contract.cue: plain data unified with
//// contract.#Contract, variables and file inputs sorted by name.

import docuconf/internal/meta.{type FileMeta, type VarMeta}
import docuconf/json.{type Json}
import gleam/float
import gleam/int
import gleam/list
import gleam/option.{None, Some}
import gleam/string

pub const sdk_name = "docuconf"

// x-release-please-start-version
pub const sdk_version = "0.1.0"

// x-release-please-end

pub fn render(
  name: String,
  package: String,
  app_version: option.Option(String),
  vars: List(VarMeta),
  files: List(FileMeta),
) -> String {
  let metadata =
    list.flatten([
      [#("name", json.String(name))],
      case app_version {
        Some(v) -> [#("appVersion", json.String(v))]
        None -> []
      },
      [
        #(
          "generator",
          json.Object([
            #("language", json.String("gleam")),
            #("sdk", json.String(sdk_name)),
            #("version", json.String(sdk_version)),
          ]),
        ),
      ],
    ])
  let vars =
    vars
    |> list.sort(fn(a, b) { string.compare(a.name, b.name) })
    |> list.map(fn(v) { #(v.name, json.Object(var_fields(v))) })
  let files =
    files
    |> list.sort(fn(a, b) { string.compare(a.name, b.name) })
    |> list.map(fn(f) { #(f.name, json.Object(file_fields(f))) })
  let body =
    list.flatten([
      [
        #("apiVersion", json.String("docuconf.dev/v1alpha1")),
        #("kind", json.String("ConfigContract")),
        #("metadata", json.Object(metadata)),
        #("vars", json.Object(vars)),
      ],
      case files {
        [] -> []
        _ -> [#("files", json.Object(files))]
      },
    ])
  "// Code generated by docuconf. DO NOT EDIT.\npackage "
  <> package
  <> "\n\nimport \"docuconf.dev/contract\"\n\ncontract.#Contract & "
  <> value(json.Object(body), 0)
  <> "\n"
}

fn opt(cond: Bool, field: #(String, Json)) -> List(#(String, Json)) {
  case cond {
    True -> [field]
    False -> []
  }
}

fn some(o: option.Option(a), key: String, f: fn(a) -> Json) {
  case o {
    Some(x) -> [#(key, f(x))]
    None -> []
  }
}

fn var_fields(v: VarMeta) -> List(#(String, Json)) {
  list.flatten([
    [
      #("type", json.String(v.type_)),
      #("description", json.String(v.description)),
    ],
    opt(v.required, #("required", json.Bool(True))),
    opt(v.secret, #("secret", json.Bool(True))),
    some(v.group, "group", json.String),
    opt(v.examples != [], #("examples", json.array(v.examples, json.String))),
    some(v.config_key, "configKey", json.String),
    v.fields,
    case v.secret {
      True -> []
      False -> some(v.default, "default", fn(d) { d })
    },
    some(v.deprecated, "deprecated", fn(m) {
      json.Object([#("message", json.String(m))])
    }),
  ])
}

fn file_fields(f: FileMeta) -> List(#(String, Json)) {
  list.flatten([
    [#("type", json.String(f.type_))],
    some(f.format, "format", json.String),
    [#("description", json.String(f.description))],
    opt(f.required, #("required", json.Bool(True))),
    opt(f.secret, #("secret", json.Bool(True))),
    some(f.group, "group", json.String),
    [#("path", json.String(f.path))],
    some(f.path_env, "pathEnv", json.String),
    some(f.max_size, "maxSize", json.Int),
    f.fields,
  ])
}

fn tabs(n: Int) -> String {
  string.repeat("\t", n)
}

fn scalar(j: Json) -> Bool {
  case j {
    json.Array(_) | json.Object(_) -> False
    _ -> True
  }
}

fn value(j: Json, ind: Int) -> String {
  case j {
    json.Object([]) -> "{}"
    json.Object(fields) ->
      "{\n"
      <> string.concat(
        list.map(fields, fn(f) {
          tabs(ind + 1) <> label(f.0) <> ": " <> value(f.1, ind + 1) <> "\n"
        }),
      )
      <> tabs(ind)
      <> "}"
    json.Array([]) -> "[]"
    json.Array(items) ->
      case list.all(items, scalar) {
        True -> "[" <> string.join(list.map(items, value(_, ind)), ", ") <> "]"
        False ->
          "[\n"
          <> string.concat(
            list.map(items, fn(i) {
              tabs(ind + 1) <> value(i, ind + 1) <> ",\n"
            }),
          )
          <> tabs(ind)
          <> "]"
      }
    json.Float(f) -> cue_float(f)
    json.Int(i) -> int.to_string(i)
    _ -> json.to_string(j)
  }
}

fn cue_float(f: Float) -> String {
  let s = float.to_string(f)
  case string.contains(s, "e") && !string.contains(s, ".") {
    True -> string.replace(s, "e", ".0e")
    False -> s
  }
}

const keywords = [
  "package", "import", "for", "in", "if", "let", "true", "false", "null", "_",
  "div", "mod", "quo", "rem",
]

const letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

fn label(k: String) -> String {
  let ident = case string.to_graphemes(k) {
    [first, ..rest] ->
      string.contains(letters, first)
      && list.all(rest, fn(c) { string.contains(letters <> "0123456789_", c) })
    [] -> False
  }
  case ident && !list.contains(keywords, k) {
    True -> k
    False -> json.quote(k)
  }
}
